/**
 * DATA KATALOG ITEM BEBEY STORE
 */
module.exports = [
    // 1. Skin Fish It
    { "id": "skin_aether_monarch", "name": "Aether Monarch", "price": 176000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_aurelian_bow", "name": "Aurelian Bow", "price": 15000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_ban_hammer", "name": "Ban Hammer", "price": 18000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_binary_edge", "name": "Binary Edge", "price": 14000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_blackhole_sword", "name": "Blackhole Sword", "price": 12000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_blossom_guitar", "name": "Blossom Guitar", "price": 60000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_bunny_summoner", "name": "Bunny Summoner", "price": 57000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_butterfly_sword", "name": "Butterfly Sword", "price": 34000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_candy_cane", "name": "Candy Cane", "price": 42000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_chromatic_katana", "name": "Chromatic Katana", "price": 16000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_cloud_weaver", "name": "Cloud Weaver", "price": 11000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_corruption_edge", "name": "Corruption Edge", "price": 11000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_crescendo_scythe", "name": "Crescendo Scythe", "price": 11000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_cursed_soul", "name": "Cursed Soul", "price": 6000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_dragon_spirit", "name": "Dragon Spirit", "price": 6000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_dragonmaster_scythe", "name": "Dragonmaster Scythe", "price": 28000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_draconic_soul", "name": "Draconic Soul", "price": 40000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_eclipse_katana", "name": "Eclipse Katana", "price": 15000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_electric_guitar", "name": "Electric Guitar", "price": 137000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_empyrean_staff", "name": "Empyrean Staff", "price": 63000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_enlightened", "name": "Enlightened", "price": 74000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_etereal_flower", "name": "Etereal Flower", "price": 16000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_ethereal_sword", "name": "Ethereal Sword", "price": 12000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_frozen_krampus", "name": "Frozen Krampus", "price": 10000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_galaxy_conqueror", "name": "Galaxy Conqueror", "price": 11000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_golden_clock", "name": "Golden Clock", "price": 78000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_heartfel_blade", "name": "Heartfel Blade", "price": 9000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_holy_trident", "name": "Holy Trident", "price": 36000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_kitty_guitar", "name": "Kitty Guitar", "price": 35000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_kraken_anchor", "name": "Kraken Anchor", "price": 6000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_oceanic_harpoon", "name": "Oceanic Harpoon", "price": 38000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_overdrive", "name": "Overdrive", "price": 38000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_princess_parasol", "name": "Princess Parasol", "price": 27000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_reaver_scythe", "name": "Reaver Scythe", "price": 10000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_serpents_trident", "name": "Serpent’s Trident", "price": 29000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_soul_scythe", "name": "Soul Scythe", "price": 13000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_spirit_staff", "name": "Spirit Staff", "price": 8000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_sunshine_cello", "name": "Sunshine Cello", "price": 50000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_the_vanquisher", "name": "The Vanquisher", "price": 20000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_undead_guitar", "name": "Undead Guitar", "price": 225000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_void_guitar", "name": "Void Guitar", "price": 45000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_void_kraken", "name": "Void Kraken", "price": 10000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_world_tour", "name": "World Tour", "price": 42000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "skin_divine_blade", "name": "Divine Blade", "price": 7000, "category": "Skin Fish It", "emoji": "🗡️", "requireUsername": true, "requireLimitCheck": false },

    // 2. Pet Fish It
    { "id": "pet_axolot", "name": "Axolot", "price": 130000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_capybara", "name": "Capybara", "price": 10000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_comet_cub", "name": "Comet Cub", "price": 1000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_cow", "name": "Cow", "price": 1000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_frog", "name": "Frog", "price": 1000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_gajah", "name": "Gajah", "price": 2000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_kitsune", "name": "Kitsune", "price": 280000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_lynx", "name": "Lynx", "price": 1000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_moonkin", "name": "Moonkin", "price": 1000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_penguin", "name": "Penguin", "price": 35000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_prismalune", "name": "Prismalune", "price": 275000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_ringed_phyton", "name": "Ringed Phyton", "price": 35000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_starbound_pup", "name": "Starbound Pup", "price": 15000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_stellar_hedgehog", "name": "Stellar Hedgehog", "price": 20000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_tiger", "name": "Tiger", "price": 1000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_unicorn", "name": "Unicorn", "price": 25000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },
    { "id": "pet_wolf", "name": "Wolf", "price": 1000, "category": "Pet Fish It", "emoji": "🐾", "requireUsername": true, "requireLimitCheck": false },

    // 3. Perahu & Item Fish It
    { "id": "item_ancient_moai", "name": "Ancient Moai", "price": 55000, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },
    { "id": "item_enchant_evo", "name": "Enchant Evo", "price": 100, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },
    { "id": "item_enchant_runic", "name": "Enchant Runic", "price": 1300, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },
    { "id": "item_frigid_jetski", "name": "Frigid Jetski", "price": 90000, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },
    { "id": "item_magma_boat", "name": "Magma Boat", "price": 20000, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },
    { "id": "item_mega_yacht", "name": "Mega Yacht", "price": 80000, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },
    { "id": "item_sctb", "name": "SCTB", "price": 100, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },
    { "id": "item_sharky", "name": "Sharky", "price": 40000, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },
    { "id": "item_void_craft", "name": "Void Craft", "price": 45000, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },
    { "id": "item_withering_core", "name": "Withering Core", "price": 2000, "category": "Perahu & Item Fish It", "emoji": "⛵", "requireUsername": true, "requireLimitCheck": false },

    // 4. Gamepass Fish It
    { "id": "gp_advance_luck", "name": "Advance Luck", "price": 50000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_ability_spin", "name": "Ability Spin", "price": 5000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_double_xp", "name": "Double XP", "price": 18000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_egg_spin", "name": "Egg Spin", "price": 10000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_frosted_guitar", "name": "Frosted Guitar", "price": 85000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_mutation", "name": "Mutation", "price": 30000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_sell_anywhere", "name": "Sell Anywhere", "price": 29000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_small_luck", "name": "Small Luck", "price": 6000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_vip", "name": "VIP", "price": 45000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_emote_duo_dream", "name": "Emote Duo Dream Drift", "price": 5000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_boost_x8_6h", "name": "Boost x8 6 Jam", "price": 120000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_boost_x8_12h", "name": "Boost x8 12 Jam", "price": 170000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },
    { "id": "gp_boost_x8_24h", "name": "Boost x8 24 Jam", "price": 276000, "category": "Gamepass Fish It", "emoji": "🎟️", "requireUsername": true, "requireLimitCheck": false },

    // 5. Robux Via Usn
    { "id": "rbx_100", "name": "100 Robux", "price": 15000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },
    { "id": "rbx_200", "name": "200 Robux", "price": 30000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },
    { "id": "rbx_300", "name": "300 Robux", "price": 45000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },
    { "id": "rbx_400", "name": "400 Robux", "price": 60000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },
    { "id": "rbx_500", "name": "500 Robux", "price": 75000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },
    { "id": "rbx_600", "name": "600 Robux", "price": 90000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },
    { "id": "rbx_700", "name": "700 Robux", "price": 105000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },
    { "id": "rbx_800", "name": "800 Robux", "price": 120000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },
    { "id": "rbx_900", "name": "900 Robux", "price": 135000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },
    { "id": "rbx_1000", "name": "1.000 Robux", "price": 150000, "category": "Robux Via Usn", "emoji": "💎", "requireUsername": true, "requireLimitCheck": true },

    // 6. Joki Fish It
    { "id": "joki_ghostfin", "name": "Ghostfin Rod", "price": 10000, "category": "Joki Fish It", "emoji": "⚡", "requireUsername": true, "requireLimitCheck": false },
    { "id": "joki_element", "name": "Element Rod", "price": 20000, "category": "Joki Fish It", "emoji": "⚡", "requireUsername": true, "requireLimitCheck": false },
    { "id": "joki_diamond", "name": "Diamond Rod", "price": 25000, "category": "Joki Fish It", "emoji": "⚡", "requireUsername": true, "requireLimitCheck": false },
    { "id": "joki_fullindex", "name": "Full Index", "price": 25000, "category": "Joki Fish It", "emoji": "⚡", "requireUsername": true, "requireLimitCheck": false },
    { "id": "joki_afk", "name": "Afk Mancing / Hari", "price": 5000, "category": "Joki Fish It", "emoji": "⚡", "requireUsername": true, "requireLimitCheck": false },

    // 7. PTPT
    { "id": "ptpt_1d", "name": "1 Hari", "price": 15000, "category": "PTPT", "emoji": "🤝", "requireUsername": false, "requireLimitCheck": false },
    { "id": "ptpt_1w", "name": "1 Minggu", "price": 85000, "category": "PTPT", "emoji": "🤝", "requireUsername": false, "requireLimitCheck": false },
    { "id": "ptpt_1m", "name": "1 Bulan", "price": 300000, "category": "PTPT", "emoji": "🤝", "requireUsername": false, "requireLimitCheck": false },

    // 8. Akun Fish It
    { "id": "acc_diamond", "name": "Diamond", "price": 35000, "category": "Akun Fish It", "emoji": "👤", "requireUsername": false, "requireLimitCheck": false },
    { "id": "acc_withering", "name": "Withering", "price": 150000, "category": "Akun Fish It", "emoji": "👤", "requireUsername": false, "requireLimitCheck": false },

    // 9. Token
    { "id": "token_100", "name": "100 Token", "price": 4500, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_300", "name": "300 Token", "price": 13500, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_500", "name": "500 Token", "price": 22500, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_800", "name": "800 Token", "price": 36000, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_1000", "name": "1.000 Token", "price": 45000, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_1300", "name": "1.300 Token", "price": 58500, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_1500", "name": "1.500 Token", "price": 67500, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_1800", "name": "1.800 Token", "price": 81000, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_2000", "name": "2.000 Token", "price": 90000, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_2500", "name": "2.500 Token", "price": 112500, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_3000", "name": "3.000 Token", "price": 135000, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_5000", "name": "5.000 Token", "price": 225000, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_7500", "name": "7.500 Token", "price": 337500, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false },
    { "id": "token_10000", "name": "10.000 Token", "price": 450000, "category": "Token", "emoji": "🪙", "requireUsername": true, "requireLimitCheck": false }
];
